### ISSUE TITLE
Проверить можем ли мы писать в Statistics API всё что угодно

### ISSUE THREAD

**Issue by StraightToJaneStreet** [StraightToJaneStreet/RSLang#10]

**Comment by laiker** [comment]
@StraightToJaneStreet 


Зарегал пользователя, авторизовался, 

PUT /users/{id}/statistics с токеном положил в статистику данные в ключ options  
GET /users/{id}/statistics результат в ключе options вернулся все что положил туда
![Image](https://user-images.githubusercontent.com/24527167/185427629-5cb0b9d9-3e0b-4f1c-8e95-00934cb8f6e0.png)
