### ISSUE TITLE
Узнать какую точку кормить refreshToken-ом чтобы получить свежий token

### ISSUE THREAD

**Issue by StraightToJaneStreet** [StraightToJaneStreet/RSLang#19]

**Comment by laiker** [comment]
@StraightToJaneStreet 

Route: 
 /users/{id}/tokens

Response: 
{
  "token": "string",
  "refreshToken": "string"
}

Источник:
https://github.com/rolling-scopes-school/react-rslang-be/blob/3f5e6015286bb43a3f4e2d320fd2cd4a2259f467/src/resources/token/token.service.js#L42
