### ISSUE TITLE
Создать AuthService

### ISSUE THREAD

**Issue by StraightToJaneStreet** [StraightToJaneStreet/RSLang#3]
Создать AuthController и поместить его в DI контейнер. 
Методы:
- Login - (name: string, email: string, password: string)
- Logout - ()
- Signin - (email: string, password: string)

Каждый из методов должен менять соответствующие поля в модели

Добавить кнопки в AppBar для вызова этих методов.

**Comment by laiker** [comment]
https://github.com/StraightToJaneStreet/RSLang/pull/16
